version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:4.0.2-management
    container_name: rmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
